import type { Item } from "@/types/desktop";

export const initialItems: Item[] = [
  {
    icon: "📦",
    id: "apps",
    name: "Apps",
    type: "app",
    parentId: null,
    path: "/desktop/Apps",
    gridCellId: { id: "0-0", mobileId: "5-0" },
  },
  {
    icon: "🌐",
    id: "websites",
    name: "Web",
    type: "app",
    parentId: null,
    path: "/desktop/Web",
    link: "",
    gridCellId: { id: "1-0", mobileId: "5-1" },
  },
  {
    icon: "🎮",
    id: "games",
    name: "Games",
    type: "app",
    parentId: null,
    path: "/desktop/Games",
    link: "",
    gridCellId: { id: "2-0", mobileId: "5-2" },
  },
  // {
  //   icon: "🖥️",
  //   id: "tools",
  //   name: "CLI_Tools",
  //   type: "app",
  //   parentId: null,
  //   path: "/desktop/CLI_Tools.sh",
  //   link: "",
  //   gridCellId: { id: "3-0", mobileId: "5-3" },
  // },
  {
    icon: "ℹ️",
    id: "about",
    name: "About",
    type: "app",
    parentId: null,
    path: "/desktop/About",
    gridCellId: { id: "0-1", mobileId: "6-0" },
  },
  {
    icon: "💻",
    id: "profile",
    name: "Profile",
    type: "app",
    parentId: null,
    path: "/desktop/Profile",
    gridCellId: { id: "1-1", mobileId: "6-1" },
  },
  // {
  //   icon: "🖼️",
  //   id: "gallery",
  //   name: "Gallery",
  //   type: "folder",
  //   parentId: null,
  //   path: "/desktop/Gallery",
  //   gridCellId: "2-1",
  // },
  {
    icon: "📄",
    id: "resume",
    name: "Resume.pdf",
    type: "file",
    parentId: null,
    path: "/desktop/Resume.pdf",
    link: "/resume.pdf",
    gridCellId: { id: "0-2", mobileId: "5-3" },
  },
];
