import type { Item } from "@/types/desktop";

export const initialItems: Item[] = [
  {
    icon: "🖥️",
    id: "software",
    name: "Software Center",
    type: "app",
    parentId: null,
    path: "/desktop/Software_Center",
    gridCellId: "0-0",
  },
  {
    icon: "🌐",
    id: "websites",
    name: "Web Browser",
    type: "app",
    parentId: null,
    path: "/desktop/Browser",
    link: "",
    gridCellId: "1-0",
  },
  {
    icon: "🎮",
    id: "games",
    name: "Game Store",
    type: "app",
    parentId: null,
    path: "/desktop/Games",
    link: "",
    gridCellId: "2-0",
  },
  // {
  //   icon: "🖥️",
  //   id: "tools",
  //   name: "CLI_Tools",
  //   type: "app",
  //   parentId: null,
  //   path: "/desktop/CLI_Tools.sh",
  //   link: "",
  //   gridCellId: "3-0",
  // },
  {
    icon: "🖥️",
    id: "about-me",
    name: "About NonorOS",
    type: "app",
    parentId: null,
    path: "/desktop/About_NonorOS",
    gridCellId: "0-1",
  },
  {
    icon: "⚙️",
    id: "skills",
    name: "Task Manager",
    type: "app",
    parentId: null,
    path: "/desktop/Settings",
    gridCellId: "1-1",
  },
  // {
  //   icon: "🖼️",
  //   id: "gallery",
  //   name: "Gallery",
  //   type: "folder",
  //   parentId: null,
  //   path: "/desktop/Gallery",
  //   gridCellId: "2-1",
  // },
  {
    icon: "📄",
    id: "resume",
    name: "Resume.pdf",
    type: "file",
    parentId: null,
    path: "/desktop/Resume.pdf",
    link: "/resume.pdf", // Triggers your local public asset resume download
    gridCellId: "0-2",
  },
];
