export const websites = [
  {
    icon: "💿",
    name: "Green Light Records",
    url: "https://github.com/nonoro-official/WDD2",
    stack: "MongoDB - Express - React - Node.js",
    desc: "Green Light Records is a records shop.",
    hasReadMore: false,
    preview: "/images/codecipher-ss1.jpg",
    isIFrameBlocked: true,
  },
  {
    icon: "💬",
    name: "Roll Your Reps",
    url: "https://roll-your-reps.vercel.app",
    stack: "React - Typescript - Node.js",
    desc: "PATHFIT 4 Final - Sports Advocacy Campaign",
    hasReadMore: false,
    preview: "/images/codecipher-ss1.jpg",
    isIFrameBlocked: false,
  },
  {
    icon: "💬",
    name: "Hooman Design Corporation Mega Menu",
    url: "https://nonoro-official.github.io/vnd.github.io/",
    stack: "WordPress",
    desc: "A mega menu me and my partner made for our internship using WordPress.",
    hasReadMore: false,
    preview: "/images/codecipher-ss1.jpg",
    isIFrameBlocked: false,
  },
  {
    icon: "💬",
    name: "VND School Dating Sim",
    url: "https://nonoro-official.github.io/vnd.github.io/",
    stack: "HTML - CSS",
    desc: "This is a website about a video game that was developed in my school club Visual Novel Development Club! The video game is a visual novel dating simulator about supernatural characters in a magic school.",
    hasReadMore: true,
    preview: "/images/codecipher-ss1.jpg",
    isIFrameBlocked: false,
  },
  {
    icon: "🍋",
    name: "Personal Website",
    url: "https://nonoro-official.github.io/noahpenaranda-personalwebsite.github.io/",
    stack: "HTML - CSS",
    desc: "Personal website made for college.",
    hasReadMore: false,
    preview: "/images/codecipher-ss1.jpg",
    isIFrameBlocked: false,
  },
  {
    icon: "🍋",
    name: "Portfolio",
    url: "https://nonoro-official.github.io/portfolio/",
    stack: "HTML - CSS",
    desc: "Original portfolio website. Based from the personal website.",
    hasReadMore: false,
    preview: "/images/codecipher-ss1.jpg",
    isIFrameBlocked: false,
  },
];
